export const homepageUrl = 'https://cliptern.trieflow.com';
export const privacyUrl = 'https://cliptern.trieflow.com/privacy';
export const supportUrl = 'https://cliptern.trieflow.com/support';
export const githubUrl = homepageUrl;
export const getReleaseUrl = (version: string) => `${homepageUrl}/#version=${encodeURIComponent(version)}`;
export const compareReleasesUrl = (fromVersion: string, toVersion: string) => `${homepageUrl}/#changes=${encodeURIComponent(fromVersion)}-${encodeURIComponent(toVersion)}`;
export const licensesUrl = `${homepageUrl}/licenses.txt`;
export const discussionsUrl = supportUrl;
export const usageUrl = supportUrl;
export const faqUrl = supportUrl;
export const featureRequestUrl = supportUrl;
export const publicBugReportUrl = supportUrl;
export const troubleshootingUrl = supportUrl;
export const exportedFileNameTemplateHelpUrl = supportUrl;
export const selectSegmentByExpressionHelpUrl = supportUrl;
export const editSegmentByExpressionHelpUrl = supportUrl;
export const changeEnabledStreamsExpressionHelpUrl = supportUrl;
